"""signing workflow

Revision ID: 7d1e123462e8
Revises: bade5ffb398f
Create Date: 2026-08-15 14:37:17.170340
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7d1e123462e8'
down_revision: Union[str, None] = 'bade5ffb398f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signature_assets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signature_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signature_assets_user_id'), ['user_id'], unique=False)

    op.create_table('signature_requests',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('document_id', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('state', sa.Enum('DRAFT', 'SENT', 'DELIVERED', 'VIEWED', 'PARTIALLY_SIGNED', 'COMPLETED', 'DECLINED', 'EXPIRED', 'CANCELLED', name='signaturerequeststate', native_enum=False), nullable=False),
    sa.Column('sequential', sa.Boolean(), nullable=False),
    sa.Column('document_hash', sa.String(length=64), nullable=True),
    sa.Column('source_version', sa.Integer(), nullable=True),
    sa.Column('signed_version', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signature_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signature_requests_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signature_requests_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_signature_requests_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_sigreq_workspace_state', ['workspace_id', 'state'], unique=False)

    op.create_table('signature_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_id', sa.String(length=32), nullable=False),
    sa.Column('recipient_id', sa.String(length=32), nullable=True),
    sa.Column('actor', sa.String(length=320), nullable=True),
    sa.Column('event', sa.String(length=60), nullable=False),
    sa.Column('detail', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('document_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['signature_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signature_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signature_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_signature_events_request_id'), ['request_id'], unique=False)

    op.create_table('signature_recipients',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('request_id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('PENDING', 'DELIVERED', 'VIEWED', 'SIGNED', 'DECLINED', name='recipientstate', native_enum=False), nullable=False),
    sa.Column('access_token', sa.String(length=64), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('declined_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['signature_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id', 'email', name='uq_recipient_email')
    )
    with op.batch_alter_table('signature_recipients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signature_recipients_access_token'), ['access_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_signature_recipients_request_id'), ['request_id'], unique=False)

    op.create_table('signature_fields',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('request_id', sa.String(length=32), nullable=False),
    sa.Column('recipient_id', sa.String(length=32), nullable=True),
    sa.Column('type', sa.Enum('SIGNATURE', 'INITIAL', 'NAME', 'EMAIL', 'DATE', 'TEXT', 'CHECKBOX', 'DROPDOWN', name='signaturefieldtype', native_enum=False), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['signature_recipients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['signature_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signature_fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signature_fields_recipient_id'), ['recipient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signature_fields_request_id'), ['request_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signature_fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signature_fields_request_id'))
        batch_op.drop_index(batch_op.f('ix_signature_fields_recipient_id'))

    op.drop_table('signature_fields')
    with op.batch_alter_table('signature_recipients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signature_recipients_request_id'))
        batch_op.drop_index(batch_op.f('ix_signature_recipients_access_token'))

    op.drop_table('signature_recipients')
    with op.batch_alter_table('signature_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signature_events_request_id'))
        batch_op.drop_index(batch_op.f('ix_signature_events_created_at'))

    op.drop_table('signature_events')
    with op.batch_alter_table('signature_requests', schema=None) as batch_op:
        batch_op.drop_index('ix_sigreq_workspace_state')
        batch_op.drop_index(batch_op.f('ix_signature_requests_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_signature_requests_state'))
        batch_op.drop_index(batch_op.f('ix_signature_requests_document_id'))

    op.drop_table('signature_requests')
    with op.batch_alter_table('signature_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signature_assets_user_id'))

    op.drop_table('signature_assets')
    # ### end Alembic commands ###
