"""annotations

Revision ID: bade5ffb398f
Revises: 55f2d8f7bf6f
Create Date: 2026-08-15 11:01:33.226380
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bade5ffb398f'
down_revision: Union[str, None] = '55f2d8f7bf6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_annotations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('document_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('author_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.Enum('HIGHLIGHT', 'UNDERLINE', 'STRIKETHROUGH', 'NOTE', 'COMMENT', 'DRAWING', 'SHAPE', 'ARROW', 'TEXTBOX', 'STAMP', name='annotationkind', native_enum=False), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('rect', sa.JSON(), nullable=False),
    sa.Column('quads', sa.JSON(), nullable=False),
    sa.Column('colour', sa.String(length=20), nullable=False),
    sa.Column('opacity', sa.Float(), nullable=False),
    sa.Column('selected_text', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.String(length=32), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by', sa.String(length=32), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['document_annotations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_annotations', schema=None) as batch_op:
        batch_op.create_index('ix_annotations_document_page', ['document_id', 'page'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_annotations_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_annotations_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_annotations_workspace_id'), ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_annotations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_annotations_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_document_annotations_parent_id'))
        batch_op.drop_index(batch_op.f('ix_document_annotations_document_id'))
        batch_op.drop_index('ix_annotations_document_page')

    op.drop_table('document_annotations')
    # ### end Alembic commands ###
